# SimaCode Default Configuration
# This file contains the default configuration values for SimaCode.
# You can override these values by creating a config file in:
# - Project: .simacode/config.yaml
# - User: ~/.simacode/config.yaml

# Project information
project_name: "SimaCode Project"

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: null  # Set to a path to enable file logging
  max_file_size: 10485760  # 10MB in bytes
  backup_count: 5

# Security and permission settings
security:
  allowed_paths:
    - "."  # Current working directory
    - "/tmp"
  forbidden_paths:
    - "/etc"
    - "/sys"
    - "/proc"
    - "/dev"
    - "~/.ssh"
    - "~/.gnupg"
  require_permission_for_write: true
  max_command_execution_time: 30  # seconds

# AI provider configuration
ai:
  provider: "openai"
  api_key: null  # Will be loaded from SIMACODE_API_KEY or OPENAI_API_KEY env vars
  base_url: null  # Override for custom endpoints
  model: "gpt-4"
  temperature: 0.1
  max_tokens: 4000
  timeout: 60  # seconds

# Session management
session:
  save_sessions: true
  session_dir: "~/.simacode/sessions"
  max_sessions: 512  # Maximum number of session files to keep
  auto_cleanup: true

# Conversation context management
conversation_context:
  strategy: "compressed"  # Default to intelligent layered compression
  max_messages: 100
  max_tokens: 8000
  preserve_all: false
  recent_messages: 5
  medium_recent: 10
  compression_ratio: 0.3
  preserve_topics: true
  token_budget: 4000
  min_recent: 3
  auto_summarize: true

# ReAct 引擎配置
react:
  confirm_by_human: true  # 默认禁用人工确认
  confirmation_timeout: 300  # 确认超时时间（秒）
  allow_task_modification: true  # 允许用户修改任务
  auto_confirm_safe_tasks: false  # 自动确认安全任务


#### MCP configuration #### 
#
# Email configuration
email:
  # SMTP configuration for sending emails
  smtp:
    server: null  # SMTP server address (e.g., smtp.gmail.com)
    port: 587  # SMTP port (587 for TLS, 465 for SSL, 25 for plain)
    use_tls: true  # Use TLS encryption
    use_ssl: false  # Use SSL encryption
    timeout: 30  # Connection timeout in seconds
    username: null  # SMTP username (will be loaded from EMAIL_USERNAME env var)
    password: null  # SMTP password (will be loaded from EMAIL_PASSWORD env var)
  
  # IMAP configuration for receiving emails
  imap:
    server: null  # IMAP server address (e.g., imap.gmail.com)
    port: 993  # IMAP port (993 for SSL, 143 for plain)
    use_ssl: true  # Use SSL encryption for IMAP
    timeout: 60  # Connection timeout in seconds (longer for IMAP operations)
    username: null  # IMAP username (will be loaded from EMAIL_USERNAME env var)
    password: null  # IMAP password (will be loaded from EMAIL_PASSWORD env var)
  
  # Email security settings
  security:
    max_recipients: 50  # Maximum number of recipients per email
    max_attachment_size: 26214400  # 25MB in bytes
    max_body_size: 1048576  # 1MB in bytes
    allowed_domains: []  # Allowed recipient domains (empty = allow all)
    blocked_domains: []  # Blocked recipient domains
    allowed_attachment_types: [".txt", ".pdf", ".doc", ".docx", ".xls", ".xlsx", ".jpg", ".jpeg", ".png", ".gif", ".json", ".csv", ".xml", ".zip"]
  
  # Rate limiting for email operations
  rate_limiting:
    max_emails_per_hour: 100  # Maximum emails per hour
    max_emails_per_day: 1000  # Maximum emails per day
  
  # Default email settings
  defaults:
    from_name: "SimaCode Assistant"  # Default sender name
    from_email: null  # Default sender email (will use username if not set)
