# SimaCode Default Configuration
# This file contains the default configuration values for SimaCode.
# You can override these values by creating a config file in:
# - Project: .simacode/config.yaml
# - User: ~/.simacode/config.yaml

# Project information
project_name: "SimaCode Project"

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: null  # Set to a path to enable file logging
  max_file_size: 10485760  # 10MB in bytes
  backup_count: 5

# Security and permission settings
security:
  allowed_paths: 
    - "."  # Current working directory
  forbidden_paths:
    - "/etc"
    - "/sys"
    - "/proc"
    - "/dev"
    - "~/.ssh"
    - "~/.gnupg"
  require_permission_for_write: true
  max_command_execution_time: 30  # seconds

# AI provider configuration
ai:
  provider: "openai"
  api_key: null  # Will be loaded from SIMACODE_API_KEY or OPENAI_API_KEY env vars
  base_url: null  # Override for custom endpoints
  model: "gpt-4"
  temperature: 0.1
  max_tokens: 4000
  timeout: 60  # seconds

# Session management
session:
  save_sessions: true
  session_dir: "~/.simacode/sessions"
  max_sessions: 100
  auto_cleanup: true