# MCP Server Configuration
# This file configures MCP (Model Context Protocol) servers for SimaCode

# Global MCP settings
mcp:
  enabled: true
  timeout: 30
  max_concurrent: 5
  log_level: INFO
  cache_ttl: 300
  health_check_interval: 30

# MCP server definitions
servers:
  # File System Access Server
  filesystem:
    name: filesystem
    enabled: false  # Enabled for project use
    type: stdio
    command: ["python", "tools/mcp_filesystem_server.py"]
    args: ["--root", "."]
    environment:
      WORKSPACE_ROOT: "."
    working_directory: null
    timeout: 60
    max_retries: 3
    retry_delay: 2.0
    security:
      allowed_operations: ["read", "write", "list", "create", "delete"]
      allowed_paths: [".", "/tmp"]
      forbidden_paths: ["/etc", "/usr", "/sys", "/proc", "/root"]
      max_execution_time: 60
      network_access: false

  # GitHub Integration Server
  github:
    name: github
    enabled: false  # Disabled by default - requires GITHUB_TOKEN
    type: subprocess
    command: ["npx", "@modelcontextprotocol/server-github"]
    args: ["--token", "${GITHUB_TOKEN}"]
    environment:
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
    working_directory: null
    timeout: 120
    max_retries: 3
    retry_delay: 2.0
    security:
      allowed_operations:
        - "read_repository"
        - "list_issues"
        - "list_pull_requests"
        - "read_file"
      allowed_paths: []
      forbidden_paths: []
      max_execution_time: 120
      network_access: true

  # SQLite Database Server (Example)
  sqlite:
    name: sqlite
    enabled: false  # Disabled by default
    type: subprocess
    command: ["python", "-m", "mcp_server_sqlite"]
    args: ["--db-path", "${DATABASE_PATH:-./data.db}"]
    environment:
      DATABASE_PATH: "${DATABASE_PATH:-./data.db}"
    working_directory: null
    timeout: 30
    max_retries: 3
    retry_delay: 1.0
    security:
      allowed_operations:
        - "query"
        - "schema"
      allowed_paths: ["${DATABASE_PATH:-./data.db}"]
      forbidden_paths: []
      max_execution_time: 30
      network_access: false

  # System Monitor MCP Server (Stdio)
  system_monitor:
    name: system_monitor
    enabled: false  # Enable for system monitoring demo
    type: stdio
    command: ["python", "tools/mcp_system_monitor_stdio_server.py"]
    args: []
    environment: {}
    working_directory: null
    timeout: 30
    max_retries: 3
    retry_delay: 2.0
    security:
      allowed_operations:
        - "read"
        - "execute"
      allowed_paths: ["/", "/tmp", "/var"]
      forbidden_paths: []
      max_execution_time: 30
      network_access: true

  # UI-TARS MCP Server (HTTP/WebSocket)
  ui_tars:
    name: ui_tars
    enabled: true  # WebSocket compatibility fixed
    type: websocket
    url: "${UI_TARS_MCP_URL:-ws://localhost:8080/mcp/ws}"
    headers:
      User-Agent: "SimaCode-MCP-Client/1.0"
    command: ["python", "tools/mcp_ui_tars_server.py"]  # Optional: start server locally
    args: ["--host", "localhost", "--port", "8080", "--api-key", "${AGENT_API_KEY}", "--provider", "${AGENT_PROVIDER:-volcengine}", "--model", "${AGENT_MODEL:-doubao-1-5-thinking-vision-pro-250428}"]
    environment:
      UI_TARS_MCP_URL: "${UI_TARS_MCP_URL:-ws://localhost:8080/mcp/ws}"
      TARS_COMMAND: "${TARS_COMMAND:-agent-tars}"
      AGENT_API_KEY: "${AGENT_API_KEY}"
      AGENT_PROVIDER: "${AGENT_PROVIDER:-volcengine}"
      AGENT_MODEL: "${AGENT_MODEL:-doubao-1-5-thinking-vision-pro-250428}"
    working_directory: null
    timeout: 300  # Longer timeout for UI operations
    max_retries: 3
    retry_delay: 2.0
    security:
      allowed_operations:
        - "ui_automation"
        - "web_interaction"
        - "verification_handling"
      allowed_paths: []
      forbidden_paths: []
      max_execution_time: 300
      network_access: true

  # Example HTTP/WebSocket MCP Server Template
  web_server:
    name: web_server
    enabled: false  # Disabled by default
    type: websocket
    url: "${MCP_SERVER_URL:-ws://localhost:8080/mcp}"
    command: []  # Not used for websocket type
    args: []
    environment:
      MCP_SERVER_URL: "${MCP_SERVER_URL:-ws://localhost:8080/mcp}"
    working_directory: null
    timeout: 30
    max_retries: 3
    retry_delay: 1.0
    security:
      allowed_operations: []
      allowed_paths: []
      forbidden_paths: []
      max_execution_time: 60
      network_access: true

# Configuration Notes:
# 
# 1. Environment Variables:
#    - Use ${VAR_NAME} syntax for environment variable substitution
#    - Provide defaults with ${VAR_NAME:-default_value} syntax
#    - Set environment variables before running SimaCode
#
# 2. Security:
#    - By default, most servers are disabled for security
#    - Review and configure security settings before enabling
#    - allowed_paths and forbidden_paths are enforced for file access
#    - max_execution_time prevents runaway processes
#
# 3. Server Types:
#    - subprocess: Most common, runs MCP server as child process
#    - websocket: Connects to WebSocket-based MCP server
#
# 4. To enable a server:
#    - Set enabled: true
#    - Configure required environment variables
#    - Adjust security settings as needed
#
# 5. Example environment setup:
#    export GITHUB_TOKEN="your_github_token_here"
#    export WORKSPACE_ROOT="/path/to/your/workspace"
#    export DATABASE_PATH="/path/to/your/database.db"
